version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - grade-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:             
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - grade-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # This "bakes" the IP into the Next.js build so it stops using 127.0.0.1
        - NEXT_PUBLIC_API_URL=http://54.160.148.223/api
    environment:
      - NEXT_PUBLIC_API_URL=http://54.160.148.223/api
      - BACKEND_INTERNAL_URL=http://backend:8000
    volumes:
      - ./data:/app/data
    depends_on:
      - backend
    networks:
      - grade-net

networks:
  grade-net:
    driver: bridge